/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_parcial2;

import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Usuario
 */
public class FrmPrincipal extends javax.swing.JFrame {

    DefaultTableModel modelo2 = new DefaultTableModel();
    DefaultTableModel modelo = new DefaultTableModel();
    List<Informacion> Datos = new ArrayList<>();
    
    int posicion = 0;
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        initComponents();
        setLocationRelativeTo(null);
        Titulos();
        Cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtprofesion = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        btngrabar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        Tabla3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        jScrollPane1.setForeground(new java.awt.Color(0, 255, 0));

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("DATOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(348, 38, 53, 26);

        jLabel2.setText("Profesion");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(28, 177, 53, 26);

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(28, 81, 53, 26);

        jLabel4.setText("Correo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(28, 145, 53, 26);

        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(28, 113, 53, 26);
        getContentPane().add(txtnombre);
        txtnombre.setBounds(110, 84, 150, 20);
        getContentPane().add(txttelefono);
        txttelefono.setBounds(110, 116, 150, 20);
        getContentPane().add(txtcorreo);
        txtcorreo.setBounds(110, 148, 150, 20);
        getContentPane().add(txtprofesion);
        txtprofesion.setBounds(110, 180, 150, 20);

        btnactualizar.setText("Mostrar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar);
        btnactualizar.setBounds(290, 150, 100, 23);

        btngrabar.setText("Grabar");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btngrabar);
        btngrabar.setBounds(310, 100, 71, 38);

        jLabel6.setText("Nombres");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 230, 53, 26);

        jLabel7.setText("Informacion");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 230, 80, 26);
        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 2, 2);
        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(0, 0, 2, 2);
        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(0, 0, 2, 2);

        jScrollPane6.setForeground(new java.awt.Color(0, 255, 0));

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(Tabla2);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(320, 270, 330, 190);

        jScrollPane7.setForeground(new java.awt.Color(0, 255, 0));

        Tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla3MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(Tabla3);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(50, 270, 200, 190);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        // TODO add your handling code here:
        Archivos conexion = new Archivos();
        Informacion dato = new Informacion();
        
        dato.setProfesion(txtprofesion.getText().toString());
        dato.setCorreo(txtcorreo.getText().toString());
        dato.setNombre(txtnombre.getText().toString());
        dato.setTelefono(Integer.valueOf(txttelefono.getText()));
        
        
        conexion.Agregar(dato);
        List<Informacion> Datos = conexion.getDatos();
        
        if(conexion.Grabar(Datos, 0)){
            
            JOptionPane.showMessageDialog(this, 
                    "Se registro con éxito", 
                    "Éxito",JOptionPane.INFORMATION_MESSAGE);
            CargarRegistro();
            
        }else{
            JOptionPane.showMessageDialog(this, 
                   "Error al grabar el archivo", 
                   "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        Archivos conexion = new Archivos();
        Informacion dato = new Informacion();
        
        dato.setProfesion(txtprofesion.getText().toString());
        dato.setCorreo(txtcorreo.getText().toString());
        dato.setNombre(txtnombre.getText().toString());
        dato.setTelefono(Integer.valueOf(txttelefono.getText()));
        
        Datos.set(posicion, dato);
        
        if(conexion.Grabar(Datos, 1)){
            
            JOptionPane.showMessageDialog(this, 
                    "Se actualizó con éxito", 
                    "Éxito",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
            CargarRegistro();
            
        }else{
            JOptionPane.showMessageDialog(this, 
                   "No se pudo actualizar el archivo", 
                   "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void Tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_Tabla1MouseClicked

    private void Tabla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla2MouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_Tabla2MouseClicked

    private void Tabla3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla3MouseClicked
        // TODO add your handling code here:
        int nfilas = Tabla3.getSelectedRowCount();
        int fila = 0;
        
        if(nfilas == 1){
            fila = Tabla3.getSelectedRow();
            new FrmBaseD().setVisible(true);
            
            posicion = fila;
            
            //Muestra mostrar = new FrmBaseD();
            
            String nom = Tabla3.getValueAt(fila, 0).toString();
            FrmBaseD.nombre.setText(nom);
            
            String tele = Tabla2.getValueAt(fila, 2).toString();
            FrmBaseD.Telefono.setText(tele);
            
            String corre = Tabla2.getValueAt(fila, 0).toString();
            FrmBaseD.Correo.setText(corre);
            
            String prof = Tabla2.getValueAt(fila, 1).toString();
            FrmBaseD.Profesion.setText(prof);
        }
    }//GEN-LAST:event_Tabla3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    private void Cargar(){
        Archivos conexion = new Archivos();
        if(conexion.Verificar()){
            if(conexion.Leer()){
                Datos = conexion.getDatos();
                CargarRegistro();
            }else{
                JOptionPane.showMessageDialog(this, 
                    "No se puede leer la informacion", 
                    "Error",JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, 
                    "No existe el archivo", 
                    "ERROR",JOptionPane.INFORMATION_MESSAGE);
        }
    
    }
    
    private void Titulos(){
        modelo2.addColumn("Correo");
        modelo2.addColumn("Profesion");
        modelo2.addColumn("Telefono");
        
        Tabla3.setModel(modelo2);
        
        modelo.addColumn("Nombre");
        Tabla1.setModel(modelo);
    }
    
    private void CargarRegistro(){
        
        //TABLA DATOS
        Object[] filatabla = new Object [3];
        for(Informacion dato : Datos){
            
            filatabla[0] = dato.getCorreo();
            filatabla[1] = dato.getProfesion();
            filatabla[2] = dato.getTelefono();
            
            modelo2.addRow(filatabla);
        }
        
        Tabla2.setModel(modelo2);
        
        //TABLA NOMBRE
        Object[] fila = new Object[1];
        for(Informacion dato : Datos){
            fila[0] = dato.getNombre();
            
            modelo.addRow(fila);
        }
        
        Tabla3.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JTable Tabla2;
    private javax.swing.JTable Tabla3;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprofesion;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables

   
}
